# Settings for Netlify CMS
# full guide for Gatsby & Netlify CMS here: https://www.gatsbyjs.org/docs/netlify-cms/

backend:
  name: git-gateway
  # Replace this with your github-username/repo-name
  # then do the netlify setup here: https://www.netlify.com/docs/authentication-providers/#using-an-authentication-provider

media_folder: src/content/assets
public_folder: assets

# CMS File Structures
collections:
  - name: posts
    label: Posts
    folder: src/content/students
    create: true
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: student}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - name: about
        label: About Page
        file: src/content/about.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: post}
          - { name: title, label: Title }
          - { name: description, label: Description, widget: text }
